
import java.awt.Color;
import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ButtonMasher.java
 *
 * Created on May 24, 2010, 7:13:14 PM
 */

/**
 *
 * @author bare bones
 */
public class ButtonMasher extends javax.swing.JFrame
{
  private int count = 0;
  public final String TITLE = "Blue Husky's Button Masher";
  Timer timer = new Timer(1, new java.awt.event.ActionListener()
  {
    public float count = 0;
    public boolean yes = true;
    public void actionPerformed(java.awt.event.ActionEvent evt)
    {
      theButton.setBackground(Color.getHSBColor(count, 1 - count, count));
      if (yes)
        count = count + (float).01;
      else
        count = count - (float).01;
      if (count > 1)
        yes = !yes;
      System.err.print(count + " ");

    }
  });

    /** Creates new form ButtonMasher */
    public ButtonMasher()
    {
      initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    theButton = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle(TITLE);

    theButton.setText(count + "!");
    theButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        theButtonActionPerformed(evt);
      }
    });

    jButton1.setBackground(new java.awt.Color(255, 0, 0));
    jButton1.setText("go away!");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
      .addComponent(theButton, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(theButton, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void theButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_theButtonActionPerformed
    {//GEN-HEADEREND:event_theButtonActionPerformed
      count++;
      theButton.setText(count + "!");
      System.out.println(count % 50);
      theButton.setBackground(null);
      timer.setDelay(count);
      if (count % 50 != 0)
        timer.stop();
      else
        timer.start();
    }//GEN-LAST:event_theButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ButtonMasher().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton theButton;
  // End of variables declaration//GEN-END:variables

}
