
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ColorChooser.java
 *
 * Created on Apr 30, 2010, 1:58:39 AM
 */

/**
 *
 * @author bare bones
 */
public class ColorChooser extends javax.swing.JFrame {

  static void setColorButton1Background(Color input)
  {
    applyColorButton1.setBackground(input);
    applyColorButton1.repaint();
  }
  static void setColorButton2Background(Color input)
  {
    applyColorButton2.setBackground(input);
    applyColorButton2.repaint();
  }
  private Color selectedColor;

    /** Creates new form ColorChooser */
    public ColorChooser() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    colorTabbedPane = new javax.swing.JTabbedPane();
    presetTabbedPane = new javax.swing.JTabbedPane();
    presetDefaultTab = new javax.swing.JPanel();
    presetP1Button1 = new javax.swing.JButton();
    presetP2Button1 = new javax.swing.JButton();
    presetClassicTab = new javax.swing.JPanel();
    presetP1Button4 = new javax.swing.JButton();
    presetP2Button4 = new javax.swing.JButton();
    presetBWTab = new javax.swing.JPanel();
    presetP1Button2 = new javax.swing.JButton();
    presetP2Button2 = new javax.swing.JButton();
    presetRedVsBlueTab = new javax.swing.JPanel();
    presetP1Button6 = new javax.swing.JButton();
    presetP2Button6 = new javax.swing.JButton();
    presetMintCTab = new javax.swing.JPanel();
    presetP1Button3 = new javax.swing.JButton();
    presetP2Button3 = new javax.swing.JButton();
    presetSupuhNightTab = new javax.swing.JPanel();
    presetP1Button5 = new javax.swing.JButton();
    presetP2Button5 = new javax.swing.JButton();
    jColorChooser1 = new javax.swing.JColorChooser();
    jPanel2 = new javax.swing.JPanel();
    applyColorButton1 = new javax.swing.JButton();
    applyColorButton2 = new javax.swing.JButton();

    setTitle(Main.trans("Color chooser - ", "Farbe-Auswahl - ", "Selector de color - ") + Main.TITLE);
    setBackground(new Color(240, 240, 240, 0));
    setResizable(false);

    colorTabbedPane.setMinimumSize(new java.awt.Dimension(434, 480));

    presetTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

    presetDefaultTab.setOpaque(false);

    presetP1Button1.setBackground(new java.awt.Color(26, 26, 26));
    presetP1Button1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP1Button1ActionPerformed(evt);
      }
    });

    presetP2Button1.setBackground(Color.getHSBColor((float)0.59166666666666666666666666666667, (float).58, (float).74));
    presetP2Button1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP2Button1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout presetDefaultTabLayout = new javax.swing.GroupLayout(presetDefaultTab);
    presetDefaultTab.setLayout(presetDefaultTabLayout);
    presetDefaultTabLayout.setHorizontalGroup(
      presetDefaultTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(presetDefaultTabLayout.createSequentialGroup()
        .addComponent(presetP1Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        .addComponent(presetP2Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    presetDefaultTabLayout.setVerticalGroup(
      presetDefaultTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(presetP1Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
      .addComponent(presetP2Button1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
    );

    presetTabbedPane.addTab("Default", null, presetDefaultTab, Main.trans("The default colors", "Die Standardfarben", "Los colores por defecto"));

    presetClassicTab.setOpaque(false);

    presetP1Button4.setBackground(new java.awt.Color(0, 0, 0));
    presetP1Button4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP1Button4ActionPerformed(evt);
      }
    });

    presetP2Button4.setBackground(new java.awt.Color(255, 0, 0));
    presetP2Button4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP2Button4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout presetClassicTabLayout = new javax.swing.GroupLayout(presetClassicTab);
    presetClassicTab.setLayout(presetClassicTabLayout);
    presetClassicTabLayout.setHorizontalGroup(
      presetClassicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(presetClassicTabLayout.createSequentialGroup()
        .addComponent(presetP1Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        .addComponent(presetP2Button4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    presetClassicTabLayout.setVerticalGroup(
      presetClassicTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(presetP1Button4, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
      .addComponent(presetP2Button4, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
    );

    presetTabbedPane.addTab("Classic", null, presetClassicTab, Main.trans("Classic colors", "Klassischen Farben", "Colores clásicos"));

    presetBWTab.setOpaque(false);

    presetP1Button2.setBackground(new java.awt.Color(0, 0, 0));
    presetP1Button2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP1Button2ActionPerformed(evt);
      }
    });

    presetP2Button2.setBackground(new java.awt.Color(255, 255, 255));
    presetP2Button2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP2Button2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout presetBWTabLayout = new javax.swing.GroupLayout(presetBWTab);
    presetBWTab.setLayout(presetBWTabLayout);
    presetBWTabLayout.setHorizontalGroup(
      presetBWTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(presetBWTabLayout.createSequentialGroup()
        .addComponent(presetP1Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        .addComponent(presetP2Button2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    presetBWTabLayout.setVerticalGroup(
      presetBWTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(presetP1Button2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
      .addComponent(presetP2Button2, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
    );

    presetTabbedPane.addTab("Black & White", null, presetBWTab, Main.trans("Black and white", "Schwarz und weiß", "Blanco y negro"));

    presetRedVsBlueTab.setOpaque(false);

    presetP1Button6.setBackground(new java.awt.Color(255, 0, 0));
    presetP1Button6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP1Button6ActionPerformed(evt);
      }
    });

    presetP2Button6.setBackground(new java.awt.Color(0, 0, 153));
    presetP2Button6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP2Button6ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout presetRedVsBlueTabLayout = new javax.swing.GroupLayout(presetRedVsBlueTab);
    presetRedVsBlueTab.setLayout(presetRedVsBlueTabLayout);
    presetRedVsBlueTabLayout.setHorizontalGroup(
      presetRedVsBlueTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(presetRedVsBlueTabLayout.createSequentialGroup()
        .addComponent(presetP1Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        .addComponent(presetP2Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    presetRedVsBlueTabLayout.setVerticalGroup(
      presetRedVsBlueTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(presetP1Button6, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
      .addComponent(presetP2Button6, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
    );

    presetTabbedPane.addTab("<html><center>Red vs.<br>Blue</center></html>", null, presetRedVsBlueTab, Main.trans("Red Versus Blue", "Rot Kämpfe blau", "Lucha de Rojo y Azul"));

    presetMintCTab.setOpaque(false);

    presetP1Button3.setBackground(new java.awt.Color(135, 78, 36));
    presetP1Button3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP1Button3ActionPerformed(evt);
      }
    });

    presetP2Button3.setBackground(new java.awt.Color(153, 255, 153));
    presetP2Button3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP2Button3ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout presetMintCTabLayout = new javax.swing.GroupLayout(presetMintCTab);
    presetMintCTab.setLayout(presetMintCTabLayout);
    presetMintCTabLayout.setHorizontalGroup(
      presetMintCTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presetMintCTabLayout.createSequentialGroup()
        .addComponent(presetP1Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(presetP2Button3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    presetMintCTabLayout.setVerticalGroup(
      presetMintCTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(presetP2Button3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
      .addComponent(presetP1Button3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
    );

    presetTabbedPane.addTab("<html><center>Mint<br>Chocolate</center></html>", null, presetMintCTab, Main.trans("Mint Chocolate", "Als Schokolade", "Menta Chocolate"));

    presetSupuhNightTab.setOpaque(false);

    presetP1Button5.setBackground(new java.awt.Color(14, 23, 33));
    presetP1Button5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP1Button5ActionPerformed(evt);
      }
    });

    presetP2Button5.setBackground(new java.awt.Color(169, 255, 0));
    presetP2Button5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        presetP2Button5ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout presetSupuhNightTabLayout = new javax.swing.GroupLayout(presetSupuhNightTab);
    presetSupuhNightTab.setLayout(presetSupuhNightTabLayout);
    presetSupuhNightTabLayout.setHorizontalGroup(
      presetSupuhNightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(presetSupuhNightTabLayout.createSequentialGroup()
        .addComponent(presetP1Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        .addComponent(presetP2Button5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    presetSupuhNightTabLayout.setVerticalGroup(
      presetSupuhNightTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(presetP1Button5, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
      .addComponent(presetP2Button5, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
    );

    presetTabbedPane.addTab("<html><center>Supuh at<br>Night</center></html>", null, presetSupuhNightTab, Main.trans("Supuh at night", "Supuh bei Nacht", "Supuh en la noche"));

    colorTabbedPane.addTab("Presets", null, presetTabbedPane, "Choose from a list of preset colors");

    jColorChooser1.setBackground(new Color(240, 240, 240, 0));
    jColorChooser1.setMinimumSize(new java.awt.Dimension(429, 480));
    jColorChooser1.setOpaque(false);
    colorTabbedPane.addTab("Custom", null, jColorChooser1, "Choose your own colors");

    applyColorButton1.setBackground(Main.tempColor1);
    applyColorButton1.setText("Set " + Main.name1 + "'s color");
    applyColorButton1.setToolTipText("Apply setting and close");
    applyColorButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        applyColorButton1ActionPerformed(evt);
      }
    });

    applyColorButton2.setBackground(Main.tempColor2);
    applyColorButton2.setText("Set " + Main.name2 + "'s color");
    applyColorButton2.setToolTipText("Apply setting and close");
    applyColorButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        applyColorButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(applyColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
        .addComponent(applyColorButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(applyColorButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(applyColorButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(colorTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(colorTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 379, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void applyColorButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_applyColorButton1ActionPerformed
    {//GEN-HEADEREND:event_applyColorButton1ActionPerformed
      if (jColorChooser1.isShowing())
        selectColor(jColorChooser1.getColor());
      if (selectedColor != null)
      {
        Main.setP1Color(selectedColor);
        applyColorButton1.setBackground(Main.tempColor1);
        applyColorButton1.repaint();
      }
      else
        JOptionPane.showMessageDialog(this, "You must select a color first", Main.trans("User error - ", "Error de usuario", "Error de usuario - ") + Main.TITLE, 2, new javax.swing.ImageIcon(getClass().getResource("/cancel.png")));
    }//GEN-LAST:event_applyColorButton1ActionPerformed

    private void applyColorButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_applyColorButton2ActionPerformed
    {//GEN-HEADEREND:event_applyColorButton2ActionPerformed
      if (jColorChooser1.isShowing())
        selectColor(jColorChooser1.getColor());
      if (selectedColor != null)
      {
        Main.setP2Color(selectedColor);
        applyColorButton2.setBackground(Main.tempColor2);
        applyColorButton2.repaint();
      }
      else
        JOptionPane.showMessageDialog(this, "You must select a color first", Main.trans("User error - ", "Error de usuario", "Error de usuario - ") + Main.TITLE, 2, new javax.swing.ImageIcon(getClass().getResource("/cancel.png")));
    }//GEN-LAST:event_applyColorButton2ActionPerformed

    private void presetP2Button1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP2Button1ActionPerformed
    {//GEN-HEADEREND:event_presetP2Button1ActionPerformed
      selectColor(presetP2Button1.getBackground());
    }//GEN-LAST:event_presetP2Button1ActionPerformed

    private void presetP1Button1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP1Button1ActionPerformed
    {//GEN-HEADEREND:event_presetP1Button1ActionPerformed
      selectColor(presetP1Button1.getBackground());
    }//GEN-LAST:event_presetP1Button1ActionPerformed

    private void presetP1Button2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP1Button2ActionPerformed
    {//GEN-HEADEREND:event_presetP1Button2ActionPerformed
      selectColor(presetP1Button2.getBackground());
    }//GEN-LAST:event_presetP1Button2ActionPerformed

    private void presetP2Button2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP2Button2ActionPerformed
    {//GEN-HEADEREND:event_presetP2Button2ActionPerformed
      selectColor(presetP2Button2.getBackground());
    }//GEN-LAST:event_presetP2Button2ActionPerformed

    private void presetP1Button3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP1Button3ActionPerformed
    {//GEN-HEADEREND:event_presetP1Button3ActionPerformed
      selectColor(presetP1Button3.getBackground());
    }//GEN-LAST:event_presetP1Button3ActionPerformed

    private void presetP2Button3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP2Button3ActionPerformed
    {//GEN-HEADEREND:event_presetP2Button3ActionPerformed
      selectColor(presetP2Button3.getBackground());
    }//GEN-LAST:event_presetP2Button3ActionPerformed

    private void presetP1Button4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP1Button4ActionPerformed
    {//GEN-HEADEREND:event_presetP1Button4ActionPerformed
      selectColor(presetP1Button4.getBackground());
    }//GEN-LAST:event_presetP1Button4ActionPerformed

    private void presetP2Button4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP2Button4ActionPerformed
    {//GEN-HEADEREND:event_presetP2Button4ActionPerformed
      selectColor(presetP2Button4.getBackground());
    }//GEN-LAST:event_presetP2Button4ActionPerformed

    private void presetP1Button5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP1Button5ActionPerformed
    {//GEN-HEADEREND:event_presetP1Button5ActionPerformed
      selectColor(presetP1Button5.getBackground());
    }//GEN-LAST:event_presetP1Button5ActionPerformed

    private void presetP2Button5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP2Button5ActionPerformed
    {//GEN-HEADEREND:event_presetP2Button5ActionPerformed
      selectColor(presetP2Button5.getBackground());
    }//GEN-LAST:event_presetP2Button5ActionPerformed

    private void presetP1Button6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP1Button6ActionPerformed
    {//GEN-HEADEREND:event_presetP1Button6ActionPerformed
      selectColor(presetP1Button6.getBackground());
    }//GEN-LAST:event_presetP1Button6ActionPerformed

    private void presetP2Button6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_presetP2Button6ActionPerformed
    {//GEN-HEADEREND:event_presetP2Button6ActionPerformed
      selectColor(presetP2Button6.getBackground());
    }//GEN-LAST:event_presetP2Button6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorChooser().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public static javax.swing.JButton applyColorButton1;
  public static javax.swing.JButton applyColorButton2;
  public static javax.swing.JTabbedPane colorTabbedPane;
  public static javax.swing.JColorChooser jColorChooser1;
  public static javax.swing.JPanel jPanel2;
  public static javax.swing.JPanel presetBWTab;
  public static javax.swing.JPanel presetClassicTab;
  public static javax.swing.JPanel presetDefaultTab;
  public static javax.swing.JPanel presetMintCTab;
  public static javax.swing.JButton presetP1Button1;
  public static javax.swing.JButton presetP1Button2;
  public static javax.swing.JButton presetP1Button3;
  public static javax.swing.JButton presetP1Button4;
  public static javax.swing.JButton presetP1Button5;
  public static javax.swing.JButton presetP1Button6;
  public static javax.swing.JButton presetP2Button1;
  public static javax.swing.JButton presetP2Button2;
  public static javax.swing.JButton presetP2Button3;
  public static javax.swing.JButton presetP2Button4;
  public static javax.swing.JButton presetP2Button5;
  public static javax.swing.JButton presetP2Button6;
  public static javax.swing.JPanel presetRedVsBlueTab;
  public static javax.swing.JPanel presetSupuhNightTab;
  public static javax.swing.JTabbedPane presetTabbedPane;
  // End of variables declaration//GEN-END:variables

  private void selectColor(Color selected)
  {
    selectedColor = selected;
  }

}
